apiVersion: v1
kind: LimitRange
metadata:
  name: demo_service-limits
  namespace: demo
  labels:
    app: demo_service
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 250m
        memory: 256Mi
